=== inniyah/quaketoogre/config.dtd
<!-- Root element -->
<!ELEMENT conversion (md2mesh|md3mesh)>

<!-- This element determines type of conversion -->
<!ELEMENT md2mesh (inputfile, outputfile, convertcoordinates?, animations?, materials?)>
<!ELEMENT md3mesh (inputfile, outputfile, convertcoordinates?, animationfile?, animations?, materials?)>

<!-- Convert vectors to Ogre coordinate system -->
<!ELEMENT convertcoordinates EMPTY>

<!-- Filenames -->
<!ELEMENT inputfile (filename)>
<!ELEMENT outputfile (filename)>
<!ELEMENT filename (#PCDATA)>

<!-- Quake 3 animation file -->
<!ELEMENT animationfile (filename, (convertall|animationname+))>
<!ELEMENT convertall EMPTY>
<!ELEMENT animationname (#PCDATA)>

<!-- Individual animation definitions -->
<!ELEMENT animations (animationsequence+)>
<!ELEMENT animationsequence (animationname, startframe, numframes, fps)>
<!ELEMENT startframe (#PCDATA)>
<!ELEMENT numframes (#PCDATA)>
<!ELEMENT fps (#PCDATA)>

<!-- Materials -->
<!ELEMENT materials (material+)>
<!ELEMENT material (materialname, submeshname, texture?)>
<!ELEMENT materialname (#PCDATA)>
<!ELEMENT submeshname (#PCDATA)>
<!ELEMENT texture (filename)>	<!-- If left out, no material script will be written -->

<!-- TODO: Add MD3 player models (lower, upper, head) -->
<!-- TODO: Add tag-to-skeleton support -->
<!-- TODO: Check if 'materials' tag is appropriate for MD2 -->

=== inniyah/quaketoogre/out/exampleconfig.xml
<?xml version="1.0"?>
<!DOCTYPE conversion SYSTEM "../config.dtd">

<conversion>
	<convertcoordinates/>

	<md3mesh>
		<inputfile>
			<filename>models/players/visor/lower.md3</filename>
		</inputfile>
		
		<outputfile>
			<filename>lower.mesh.xml</filename>
		</outputfile>
		
		<referenceframe>0</referenceframe>
		
		<animationfile>
			<filename>models/players/visor/animation.cfg</filename>
			<convertlegs/>
			<!--<convertselection>
				<animationname>LEGS_WALK</animationname>
				<animationname>LEGS_RUN</animationname>
			</convertselection>-->
		</animationfile>
		
		<animations>
			<animationsequence>
				<animationname>swim</animationname>
				<startframe>129</startframe>
				<numframes>10</numframes>
				<fps>15</fps>
			</animationsequence>
			<animationsequence>
				<animationname>die</animationname>
				<startframe>0</startframe>
				<numframes>30</numframes>
				<fps>25</fps>
			</animationsequence>
		</animations>
		
		<materials>
			<material>
				<submeshname>l_legs</submeshname>
				<materialname>visor/lower</materialname>
			</material>
		</materials>
	</md3mesh>
</conversion>

=== inniyah/quaketoogre/out/md5exampleconfig.xml
<?xml version="1.0"?>
<!DOCTYPE conversion SYSTEM "../config.dtd">

<conversion>
	<convertcoordinates/>

	<md5mesh>
		<inputfile>
			<filename>bernie/bernie.md5mesh</filename>
		</inputfile>
		
		<outputfile>
			<filename>bernie.mesh.xml</filename>
		</outputfile>
		
		<md5animations>
			<md5anim>
				<animationname>Spit Attack</animationname>
				<filename>spit_attack1.md5anim</filename>
			</md5anim>
		</md5animations>

		<materials>
			<material>
				<submeshname>something</submeshname>
				<materialname>md5models/bernie/something</materialname>
			</material>
		</materials>
	</md5mesh>
</conversion>

=== inniyah/quaketoogre/out/q2exampleconfig.xml
<?xml version="1.0"?>
<!DOCTYPE conversion SYSTEM "../config.dtd">

<conversion>
    <convertcoordinates/>

	<md2mesh>
		<inputfile>players/male/tris.md2</inputfile>
		<outputfile>q2male.mesh.xml</outputfile>

		<referenceframe>0</referenceframe>

		<animations>
			<animationsequence>
				<animationname>run</animationname>
				<startframe>40</startframe>
				<numframes>6</numframes>
				<fps>10</fps>
			</animationsequence>
			<animationsequence>
				<animationname>taunt</animationname>
				<startframe>95</startframe>
				<numframes>17</numframes>
				<fps>10</fps>
			</animationsequence>
		</animations>

		<materialname>q2male/skin</materialname>
	</md2mesh>
</conversion>

=== inniyah/quaketoogre/exampleconfig.xml
<?xml version="1.0"?>
<!DOCTYPE conversion SYSTEM "../config.dtd">

<conversion>
	<convertcoordinates/>

	<md3mesh>
		<inputfile>
			<filename>models/players/visor/lower.md3</filename>
		</inputfile>
		<outputfile>
			<filename>lower.mesh.xml</filename>
		</outputfile>
		
		<animationfile>
			<filename>models/players/visor/animation.cfg</filename>
			<animationgroup><grouplower/></animationgroup>
			<convertall/>
			<!--<animationname>LEGS_WALK</animationname>
			<animationname>LEGS_RUN</animationname>-->
		</animationfile>
		
		<!--<animations>
			<animationsequence>
				<animationname>swim</animationname>
				<startframe>0</startframe>
				<numframes>20</numframes>
				<fps>15</fps>
			</animationsequence>
			<animationsequence>
				<animationname>die</animationname>
				<startframe>40</startframe>
				<numframes>30</numframes>
				<fps>20</fps>
			</animationsequence>
		</animations>-->
		
		<materials>
			<material>
				<materialname>visor/lower</materialname>
				<submeshname>l_legs</submeshname>
				<texture>
					<filename>visor.tga</filename>
				</texture>
			</material>
		</materials>
	</md3mesh>
</conversion>
